# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Matt Whalley
tagline:          Matt Whalley - User Experience Designer
description:      'USER EXPERIENCE DESIGNER<br><br><br><br><em>Welcome to my personal piece of internet</em> 👋'
url:              http://mttwhlly.github.io
baseurl:          /

author:
  name:           'Matt Whalley'
  url:            https://twitter.com/mttwhlly

paginate:         5

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mttwhlly.github.io
