# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Matt Whalley
tagline:          User Experience Designer
description:      'Well hello there & welcome to my personal piece of the internet. 👋<br><br>
  
I’m glad you’re here.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Matt Whalley'
  url:            https://twitter.com/mttwhlly

paginate:         5

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
